# Generated by Django 3.2.4 on 2022-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_imembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='icity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mncity', models.CharField(max_length=30)),
                ('mndate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='imembership',
            name='madd',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imembership',
            name='mname',
            field=models.CharField(max_length=50),
        ),
    ]
