# Generated by Django 3.2.4 on 2022-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220905_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icity',
            name='mncity',
            field=models.CharField(max_length=20),
        ),
    ]
