# Generated by Django 3.2.4 on 2022-09-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_icity_mncity'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityn', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='icity',
        ),
    ]
