# Generated by Django 3.2.4 on 2022-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='icountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcountry', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
