# Generated by Django 3.2.4 on 2022-09-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_istate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icountry',
            old_name='dcountry',
            new_name='countryd',
        ),
    ]
